name: "Branch Assistant"
on:
  push:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        if: ${{ github.base_ref != 'main' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Pls create PR to branch `main`
      - name: "Branch check Assistant"
        shell: bash
        run: |
          echo $GITHUB_BASE_REF
          if [ "$GITHUB_BASE_REF" == "main" ]; then
            exit 0
          else
            exit 1
          fi
          
