name: "Branch Assistant"
on:
  push:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "Branch check Assistant"
        shell: bash
        run: |
          echo $GITHUB_BASE_REF
          if [ "$GITHUB_BASE_REF" == "feat/branch-check" ]; then
            echo "GITHUB_BASE_REF is 'feat/branch-check'"
            exit 0
          else
            echo "GITHUB_BASE_REF is not 'feat/branch-check'"
            exit 1
          fi
          
